### ISSUE TITLE
Login doesn't work on newest Version

### ISSUE THREAD

**Issue by SunflowerFuchs** [teaminkling/mac-spotify-np#71]
Problem:
Login does not go past the authorization screen, request gets cancelled according to console.
I reinstalled and cleared the data, and then got stuck on the login screen with the same request getting cancelled.
![image](https://user-images.githubusercontent.com/18332886/133973650-978fb734-7b9c-4fcb-8194-7a00fe0836fc.png)

Reproduction:
Fresh install (and deleting the data in ~/Library/Application Support/now-playing-for-spotify/), then try to log in.

Workaround:
Install v0.8.1, log in, then switch back to v0.9.1

**Comment by paced** [comment]
Yeah, that's a critical bug. I thought I had fixed that `v0.9.0` but if it's happening again I'll need to rush out the new authentication flow.

Thank you for reporting this @SunflowerFuchs! I'm glad the workaround works, but I will report back with a new version as soon as possible.

**Comment by paced** [comment]
A fix has been created and `v0.10.0` will be notarised and uploaded shortly (ETA < 2 hours).

**Comment by paced** [comment]
@SunflowerFuchs `v0.10.0` was released with no regression issues, and fixes this problem. Please test it and let me know if there are any additional defects.

[Here's a link](https://github.com/teaminkling/mac-spotify-np/releases/tag/v0.10.0) but you should be able to update in-app.

**Comment by SunflowerFuchs** [comment]
Just updated to v0.10.0, can confirm it works perfectly. 
Thank you!
